package com.increff.pos.spring;

import lombok.Getter;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

/**
 * ApplicationProperties class centralizes all application configuration properties.
 * This class reads values from employee.properties and provides them as autowired properties
 * to other configuration classes, making the configuration more maintainable and organized.
 * 
 * Benefits of this approach:
 * 1. Centralized configuration management
 * 2. Type-safe property access
 * 3. Better separation of concerns
 * 4. Easier testing and configuration changes
 * 5. IDE support for property names and types
 * 
 * Uses Lombok @Getter to automatically generate getter methods for all fields,
 * reducing boilerplate code while maintaining the same functionality.
 */
@Component
@Getter
public class ApplicationProperties {

    // Application properties
    @Value("${app.version:1.0}")
    private String appVersion;
    
    @Value("${app.name:Employee Application}")
    private String appName;
    
    @Value("${app.baseUrl:/}")
    private String appBaseUrl;

    // Database configuration properties
    @Value("${jdbc.driverClassName}")
    private String jdbcDriver;
    
    @Value("${jdbc.url}")
    private String jdbcUrl;
    
    @Value("${jdbc.username}")
    private String jdbcUsername;
    
    @Value("${jdbc.password}")
    private String jdbcPassword;

    // Hibernate configuration properties
    @Value("${hibernate.dialect}")
    private String hibernateDialect;
    
    @Value("${hibernate.show_sql:true}")
    private String hibernateShowSql;
    
    @Value("${hibernate.format_sql:true}")
    private String hibernateFormatSql;
    
    @Value("${hibernate.hbm2ddl.auto:update}")
    private String hibernateHbm2ddl;
    
    @Value("${hibernate.physical_naming_strategy}")
    private String namingStrategy;
    
    @Value("${hibernate.jdbc.time_zone:UTC}")
    private String hibernateTimeZone;

    // File upload configuration properties
    @Value("${spring.servlet.multipart.enabled:true}")
    private String multipartEnabled;
    
    @Value("${spring.servlet.multipart.max-file-size:10MB}")
    private String maxFileSize;
    
    @Value("${spring.servlet.multipart.max-request-size:10MB}")
    private String maxRequestSize;

    @Value("${invoice.app.url:http://localhost:9001}")
    private String invoiceAppUrl;

    @Value("${invoice.storage.path:invoices}")
    private String invoiceStoragePath;

    // Note: All getter methods are automatically generated by Lombok @Getter annotation
    // This eliminates the need for manual getter methods while maintaining the same API
    // The following methods are now automatically available:
    // - getAppVersion()
    // - getAppName()
    // - getAppBaseUrl()
    // - getJdbcDriver()
    // - getJdbcUrl()
    // - getJdbcUsername()
    // - getJdbcPassword()
    // - getHibernateDialect()
    // - getHibernateShowSql()
    // - getHibernateFormatSql()
    // - getHibernateHbm2ddl()
    // - getNamingStrategy()
    // - getHibernateTimeZone()
    // - getMultipartEnabled()
    // - getMaxFileSize()
    // - getMaxRequestSize()
} 